-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-13 12:34:41 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- Vanessa Joyce Tan
-- 30556864

set echo on 
SPOOL mau_schema_output.txt


DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibit CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE media CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

DROP TABLE status CASCADE CONSTRAINTS;

DROP TABLE style CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code         NUMBER(4) NOT NULL,
    artist_givname      VARCHAR2(30) NOT NULL,
    artist_famname      VARCHAR2(30) NOT NULL,
    artist_street       VARCHAR2(30) NOT NULL,
    artist_town         VARCHAR2(30) NOT NULL,
    artist_state        CHAR(3) NOT NULL,
    artist_phone        CHAR(10),
    artist_num_of_art   NUMBER(3) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'artist number';

COMMENT ON COLUMN artist.artist_givname IS
    'artist given name';

COMMENT ON COLUMN artist.artist_famname IS
    'artist family name';

COMMENT ON COLUMN artist.artist_street IS
    'artist street of contact address';

COMMENT ON COLUMN artist.artist_town IS
    'artist town of contact address';

COMMENT ON COLUMN artist.artist_state IS
    'artist state of contact address in abbreviation';

COMMENT ON COLUMN artist.artist_phone IS
    'artist phone number';

COMMENT ON COLUMN artist.artist_num_of_art IS
    'artist number of art in stock';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artist_code          NUMBER(4) NOT NULL,
    artwork_no           NUMBER(3) NOT NULL,
    artwork_title        VARCHAR2(80) NOT NULL,
    artwork_date_added   DATE NOT NULL,
    artwork_min_price    NUMBER(10, 2) NOT NULL,
    media_id             NUMBER(7) NOT NULL,
    style_id             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN artwork.artist_code IS
    'artist number';

COMMENT ON COLUMN artwork.artwork_no IS
    'artwork number';

COMMENT ON COLUMN artwork.artwork_title IS
    'artwork title';

COMMENT ON COLUMN artwork.artwork_date_added IS
    'artwork date added to stock';

COMMENT ON COLUMN artwork.artwork_min_price IS
    'artwork minimum price artist receives when sold';

COMMENT ON COLUMN artwork.media_id IS
    'media surrogate key';

COMMENT ON COLUMN artwork.style_id IS
    'style surrogate key';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_no,
                                                            artist_code );

CREATE TABLE customer (
    customer_id         NUMBER(7) NOT NULL,
    customer_givname    VARCHAR2(30) NOT NULL,
    customer_famname    VARCHAR2(30) NOT NULL,
    customer_street     VARCHAR2(30) NOT NULL,
    customer_town       VARCHAR2(30) NOT NULL,
    customer_state      CHAR(3) NOT NULL,
    customer_phone      CHAR(10) NOT NULL,
    customer_biz_name   VARCHAR2(30)
);

COMMENT ON COLUMN customer.customer_id IS
    'customer id';

COMMENT ON COLUMN customer.customer_givname IS
    'customer given name';

COMMENT ON COLUMN customer.customer_famname IS
    'customer family name';

COMMENT ON COLUMN customer.customer_street IS
    'cutomer street of address';

COMMENT ON COLUMN customer.customer_town IS
    'customer town of address';

COMMENT ON COLUMN customer.customer_state IS
    'customer state of address in abbreviation';

COMMENT ON COLUMN customer.customer_phone IS
    'customer phone number';

COMMENT ON COLUMN customer.customer_biz_name IS
    'customer business name';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE exhibit (
    exhibit_id                NUMBER(7) NOT NULL,
    artist_code               NUMBER(4) NOT NULL,
    artwork_no                NUMBER(3) NOT NULL,
    exhibit_start_date        DATE NOT NULL,
    exhibit_end_date          DATE,
    exhibit_catalog_feature   VARCHAR2(3) NOT NULL,
    gallery_id                NUMBER(3) NOT NULL
);

ALTER TABLE exhibit
    ADD CONSTRAINT chk_exhibit_catalog_feature CHECK ( exhibit_catalog_feature IN
    (
        'No',
        'Yes'
    ) );

COMMENT ON COLUMN exhibit.exhibit_id IS
    'exhibit surrogate key';

COMMENT ON COLUMN exhibit.artist_code IS
    'artist number';

COMMENT ON COLUMN exhibit.artwork_no IS
    'artwork number';

COMMENT ON COLUMN exhibit.exhibit_start_date IS
    'date exhibit started';

COMMENT ON COLUMN exhibit.exhibit_end_date IS
    'date exhibit ended';

COMMENT ON COLUMN exhibit.exhibit_catalog_feature IS
    'was exhibit featured in catalog';

COMMENT ON COLUMN exhibit.gallery_id IS
    'gallery id';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT nk_exhibit UNIQUE ( artist_code,
                                       artwork_no,
                                       exhibit_start_date );

CREATE TABLE gallery (
    gallery_id             NUMBER(3) NOT NULL,
    gallery_name           VARCHAR2(30) NOT NULL,
    gallery_street         VARCHAR2(30) NOT NULL,
    gallery_town           VARCHAR2(30) NOT NULL,
    gallery_state          CHAR(3) NOT NULL,
    gallery_open_time      DATE NOT NULL,
    gallery_close_time     DATE NOT NULL,
    gallery_mngr_givname   VARCHAR2(30) NOT NULL,
    gallery_mngr_famname   VARCHAR2(30) NOT NULL,
    gallery_phone          CHAR(10) NOT NULL,
    gallery_commission     NUMBER(2) NOT NULL
);

COMMENT ON COLUMN gallery.gallery_id IS
    'gallery id';

COMMENT ON COLUMN gallery.gallery_name IS
    'gallery name';

COMMENT ON COLUMN gallery.gallery_street IS
    'gallery street of address';

COMMENT ON COLUMN gallery.gallery_town IS
    'gallery town';

COMMENT ON COLUMN gallery.gallery_state IS
    'gallery state of address in abbreviation';

COMMENT ON COLUMN gallery.gallery_open_time IS
    'gallery opening time';

COMMENT ON COLUMN gallery.gallery_close_time IS
    'gallery closing time';

COMMENT ON COLUMN gallery.gallery_mngr_givname IS
    'gallery manager''s given name';

COMMENT ON COLUMN gallery.gallery_mngr_famname IS
    'gallery manager''s family name';

COMMENT ON COLUMN gallery.gallery_phone IS
    'gallery contact phone number';

COMMENT ON COLUMN gallery.gallery_commission IS
    'gallery commision as a percentage of the sale';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE media (
    media_id            NUMBER(7) NOT NULL,
    media_description   VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN media.media_id IS
    'media surrogate key';

COMMENT ON COLUMN media.media_description IS
    'media description';

ALTER TABLE media ADD CONSTRAINT media_pk PRIMARY KEY ( media_id );

ALTER TABLE media ADD CONSTRAINT nk_media UNIQUE ( media_description );

CREATE TABLE sale (
    sale_id       NUMBER(7) NOT NULL,
    sale_date     DATE NOT NULL,
    sale_price    NUMBER(10, 2) NOT NULL,
    customer_id   NUMBER(7) NOT NULL,
    exhibit_id    NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'sale id';

COMMENT ON COLUMN sale.sale_date IS
    'date of sale';

COMMENT ON COLUMN sale.sale_price IS
    'sale price';

COMMENT ON COLUMN sale.customer_id IS
    'customer id';

COMMENT ON COLUMN sale.exhibit_id IS
    'exhibit surrogate key';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibit_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE status (
    status_id     NUMBER(7) NOT NULL,
    artist_code   NUMBER(4) NOT NULL,
    artwork_no    NUMBER(3) NOT NULL,
    status_date   DATE NOT NULL,
    status_desc   VARCHAR2(30) NOT NULL,
    gallery_id    NUMBER(3)
);

ALTER TABLE status
    ADD CONSTRAINT chk_status_desc CHECK ( status_desc IN (
        'On Display',
        'Returned to Painter',
        'Shipped to Gallery',
        'Sold',
        'in MAU Warehouse'
    ) );

COMMENT ON COLUMN status.status_id IS
    'status surrogate key';

COMMENT ON COLUMN status.artist_code IS
    'artist number';

COMMENT ON COLUMN status.artwork_no IS
    'artwork number';

COMMENT ON COLUMN status.status_date IS
    'status date';

COMMENT ON COLUMN status.status_desc IS
    'status description';

COMMENT ON COLUMN status.gallery_id IS
    'gallery id';

ALTER TABLE status ADD CONSTRAINT status_pk PRIMARY KEY ( status_id );

ALTER TABLE status
    ADD CONSTRAINT nk_status UNIQUE ( artist_code,
                                      artwork_no,
                                      status_date );

CREATE TABLE style (
    style_id          NUMBER(7) NOT NULL,
    style_name        VARCHAR2(80) NOT NULL,
    style_parent_id   NUMBER(7)
);

COMMENT ON COLUMN style.style_id IS
    'style surrogate key';

COMMENT ON COLUMN style.style_name IS
    'style name';

COMMENT ON COLUMN style.style_parent_id IS
    'style surrogate key';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( style_id );

ALTER TABLE style ADD CONSTRAINT nk_style UNIQUE ( style_name );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE exhibit
    ADD CONSTRAINT artwork_exhibit FOREIGN KEY ( artwork_no,
                                                 artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE status
    ADD CONSTRAINT artwork_status FOREIGN KEY ( artwork_no,
                                                artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE sale
    ADD CONSTRAINT exhibit_sale FOREIGN KEY ( exhibit_id )
        REFERENCES exhibit ( exhibit_id );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_exhibit FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE status
    ADD CONSTRAINT gallery_status FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE artwork
    ADD CONSTRAINT media_artwork FOREIGN KEY ( media_id )
        REFERENCES media ( media_id );

ALTER TABLE artwork
    ADD CONSTRAINT style_artwork FOREIGN KEY ( style_id )
        REFERENCES style ( style_id );

ALTER TABLE style
    ADD CONSTRAINT style_style FOREIGN KEY ( style_parent_id )
        REFERENCES style ( style_id );

SPOOL off
set echo off


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
